// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'str001_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Store _$StoreFromJson(Map<String, dynamic> json) => Store(
  storeIdx: _intAny(json['storeIdx']),
  storeNm: json['storeNm'] as String,
  brandCd: json['brandCd'] as String,
  brandNm: _stringAny(json['brandNm']),
  storeCd: _stringAny(json['storeCd']),
  storeStatus: json['storeStatus'] as String,
  storeStatusNm: json['storeStatusNm'] as String,
  ownerNm: json['ownerNm'] as String,
  storeTel: json['storeTel'] as String,
  zipCd: json['zipCd'] as String,
  address: json['address'] as String,
  addressDetail: json['adressDetail'] as String? ?? '',
  contStartDt: _stringAny(json['contStartDt']),
  contEndDt: _stringAny(json['contEndDt']),
  firstContDt: json['firstContDt'] as String? ?? '',
  frFee: _stringAny(json['frFee']),
  eduFee: _stringAny(json['eduFee']),
  insuDeposit: _stringAny(json['insuDeposit']),
  contDeposit: _stringAny(json['contDeposit']),
  contManager: _stringAny(json['contManager']),
  contManagerNm: json['contManagerNm'] as String? ?? '',
  eduManager: _stringAny(json['eduManager']),
  eduManagerNm: json['eduManagerNm'] as String? ?? '',
  contArea: _stringAny(json['contArea']),
  realArea: _stringAny(json['realArea']),
  regionCd: json['regionCd'] as String? ?? '',
  regionNm: json['regionNm'] as String? ?? '',
  storeType: json['storeType'] as String? ?? '',
  storeTypeNm: json['storeTypeNm'] as String? ?? '',
  svId: _stringAny(json['svId']),
  svNm: json['svNm'] == null ? '' : _stringAny(json['svNm']),
  floor: _intAny(json['floor']),
  parkingCount: _intAny(json['parkingCount']),
  monthlyRent: _intAny(json['monthlyRent']),
  rentDeposit: _intAny(json['rentDeposit']),
  premiumFee: _intAny(json['premiumFee']),
  businessNumber: json['businessNumber'] as String? ?? '',
  notes: json['notes'] as String? ?? '',
  latitude: _coordStringFromJson(json['latitude']),
  longitude: _coordStringFromJson(json['longitude']),
);

Map<String, dynamic> _$StoreToJson(Store instance) => <String, dynamic>{
  'storeIdx': instance.storeIdx,
  'storeNm': instance.storeNm,
  'brandCd': instance.brandCd,
  'brandNm': instance.brandNm,
  'storeCd': instance.storeCd,
  'storeStatus': instance.storeStatus,
  'storeStatusNm': instance.storeStatusNm,
  'ownerNm': instance.ownerNm,
  'storeTel': instance.storeTel,
  'zipCd': instance.zipCd,
  'address': instance.address,
  'adressDetail': instance.addressDetail,
  'contStartDt': instance.contStartDt,
  'contEndDt': instance.contEndDt,
  'firstContDt': instance.firstContDt,
  'contManager': instance.contManager,
  'contManagerNm': instance.contManagerNm,
  'eduManager': instance.eduManager,
  'eduManagerNm': instance.eduManagerNm,
  'regionCd': instance.regionCd,
  'regionNm': instance.regionNm,
  'storeType': instance.storeType,
  'storeTypeNm': instance.storeTypeNm,
  'svId': instance.svId,
  'svNm': instance.svNm,
  'businessNumber': instance.businessNumber,
  'notes': instance.notes,
  'frFee': instance.frFee,
  'eduFee': instance.eduFee,
  'insuDeposit': instance.insuDeposit,
  'contDeposit': instance.contDeposit,
  'contArea': instance.contArea,
  'realArea': instance.realArea,
  'floor': instance.floor,
  'parkingCount': instance.parkingCount,
  'monthlyRent': instance.monthlyRent,
  'rentDeposit': instance.rentDeposit,
  'premiumFee': instance.premiumFee,
  'latitude': instance.latitude,
  'longitude': instance.longitude,
};

HistoryEntry _$HistoryEntryFromJson(Map<String, dynamic> json) => HistoryEntry(
  chgDt: storeHistoryChgDtFromJson(json['chgDt']),
  chgContent: storeHistoryChgContentEncode(json['chgContent']),
  plainApiContent: json['content'] as String? ?? '',
  chgUserId: _stringAny(json['chgUserId']),
);
