// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'str001_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Store _$StoreFromJson(Map<String, dynamic> json) => Store(
  no: _intAny(json['id']),
  storeIdx: _intAny(json['storeIdx']),
  storeNm: json['storeNm'] as String,
  brandCd: json['brandCd'] as String,
  brandNm: _stringAny(_readBrandNm(json, 'brandNm')),
  storeCd: json['storeCd'] as String,
  storeStatus: json['storeStatus'] as String,
  storeStatusNm: json['storeStatusNm'] as String,
  ownerNm: json['ownerNm'] as String,
  storeTel: json['storeTel'] as String,
  zipCd: json['zipCd'] as String,
  address: json['address'] as String,
  addressDetail: json['adressDetail'] as String? ?? '',
  contStartDt: _stringAny(_readContStart(json, 'contStartDt')),
  contEndDt: _stringAny(_readContEnd(json, 'contEndDt')),
  firstContDt: json['firstContDt'] as String? ?? '',
  frFee: _stringAny(json['frFee']),
  eduFee: _stringAny(json['eduFee']),
  insuDeposit: _stringAny(json['insuDeposit']),
  contDeposit: _stringAny(json['contDeposit']),
  contManager: json['contManager'] as String? ?? '',
  eduManager: json['eduManager'] as String? ?? '',
  contArea: _stringAny(json['contArea']),
  realArea: _stringAny(json['realArea']),
  regionCd: json['regionCd'] as String? ?? '',
  regionNm: json['regionNm'] as String? ?? '',
  storeType: json['storeType'] as String? ?? '',
  storeTypeNm: json['storeTypeNm'] as String? ?? '',
  svId: _stringAny(_readSvId(json, 'svId')),
  floor: _intAny(json['floor']),
  parkingCount: _intAny(json['parkingCount']),
  monthlyRent: _intAny(json['monthlyRent']),
  rentDeposit: _intAny(json['rentDeposit']),
  premiumFee: _intAny(json['premiumFee']),
  businessNumber: json['businessNumber'] as String? ?? '',
  notes: json['notes'] as String? ?? '',
  latitude: json['latitude'] as String?,
  longitude: json['longitude'] as String?,
);

Map<String, dynamic> _$StoreToJson(Store instance) => <String, dynamic>{
  'id': instance.no,
  'storeIdx': instance.storeIdx,
  'storeNm': instance.storeNm,
  'brandCd': instance.brandCd,
  'brandNm': instance.brandNm,
  'storeCd': instance.storeCd,
  'storeStatus': instance.storeStatus,
  'storeStatusNm': instance.storeStatusNm,
  'ownerNm': instance.ownerNm,
  'storeTel': instance.storeTel,
  'zipCd': instance.zipCd,
  'address': instance.address,
  'adressDetail': instance.addressDetail,
  'contStartDt': instance.contStartDt,
  'contEndDt': instance.contEndDt,
  'firstContDt': instance.firstContDt,
  'regionCd': instance.regionCd,
  'regionNm': instance.regionNm,
  'storeType': instance.storeType,
  'storeTypeNm': instance.storeTypeNm,
  'svId': instance.svId,
  'businessNumber': instance.businessNumber,
  'notes': instance.notes,
  'frFee': instance.frFee,
  'eduFee': instance.eduFee,
  'insuDeposit': instance.insuDeposit,
  'contDeposit': instance.contDeposit,
  'contManager': instance.contManager,
  'eduManager': instance.eduManager,
  'contArea': instance.contArea,
  'realArea': instance.realArea,
  'floor': instance.floor,
  'parkingCount': instance.parkingCount,
  'monthlyRent': instance.monthlyRent,
  'rentDeposit': instance.rentDeposit,
  'premiumFee': instance.premiumFee,
  'latitude': instance.latitude,
  'longitude': instance.longitude,
};

HistoryEntry _$HistoryEntryFromJson(Map<String, dynamic> json) => HistoryEntry(
  chgDt: storeHistoryChgDtFromJson(_readChgDtHist(json, 'chgDt')),
  chgContent: storeHistoryChgContentEncode(json['chgContent']),
  plainApiContent: json['content'] as String? ?? '',
  chgUserId: _stringAny(_readChgUserHist(json, 'chgUserId')),
);
